### ISSUE TITLE
User cannot verify email address or reset password

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#152] opened 2019-05-24 02:52 UTC
Seems we have a problem with old user names and the new web app:

“I have a critical  issue to sign-up OpenChain Conformance Website.
I cannnot verify my email address. I also cannot reset my password.
Here is my status;
  + I tried to sign-up to Conformance web site a coulpe of month ago. But I haven't finish the sign-up process. (I forgot to verify my email address.)
  + When I sign-in by using my password. The system shows me "Resend Verification".
  + When I click "Yes" on "Resend Verification", the system shows "Error".

Could you check and fix this issue?
My username is "yoshi".”

**Comment by goneall** [comment] 2019-05-31 16:50
Testing this out now.  One issue is the error message when the registration expires.  It should state the resubmit the registration rather than contact the group.  Here's the message:

Registration Failed
Something seems to have gone wrong in the registration. The registration may have expired. Please contact the OpenChain team for additional help.

**Comment by goneall** [comment] 2019-05-31 16:55
It looks like the password matches fail in this scenerio.  I was able to reproduce the problem and I am getting the error "Error signing up: Passwords do not match. Please retry or reset your password".  

Log files show expected warning.

**Comment by shanecoughlan** [comment] 2019-06-03 09:04
Hi Gary! Is this closed after resolution of issue #152?

**Comment by goneall** [comment] 2019-06-03 16:04
> Hi Gary! Is this closed after resolution of issue #152?

Yes - I'll close this after I deploy the updated code

**Comment by goneall** [comment] 2019-06-03 16:18
I also manually reset the verification for the user who had the issue 10 days ago, so the user should be able to log in.

**Comment by shanecoughlan** [comment] 2019-06-03 17:00
Thank you Gary!

**Comment by goneall** [comment] 2019-07-01 03:19
Resolved in version 1.2.2 - deployed

**Closed by goneall** 2019-07-01 03:19 UTC
Labels: bug
