### ISSUE TITLE
Buttons on the bottom of the screen not working

### ISSUE THREAD

**Issue by KellyWilliams** [OpenChain-Project/Online-Self-Certification-Web-App#8] opened 2017-04-21 18:15 UTC
"Save answers" was not working as expected.  I filled out part of the survey and logged back in and my answers were not saved.  

"Download answers" did not work until I submitted the survey.

**Comment by goneall** [comment] 2017-04-21 19:41
I'll take a look at the server logs.  Thanks for reporting the issue.

On April 21, 2017 1:15:22 PM GMT-05:00, KellyWilliams <notifications@github.com> wrote:
>"Save answers" was not working as expected.  I filled out part of the
>survey and logged back in and my answers were not saved.  
>
>"Download answers" did not work until I submitted the survey.  
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenChain-Project/Online-Self-Certification-Web-App/issues/8

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by goneall** [comment] 2017-04-21 21:17
The following errors are in the log file:

INFO: Error parsing HTTP request header

Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986

        at org.apache.coyote.http11.InternalInputBuffer.parseRequestLine(InternalInputBuffer.java:189)

 

 

I’ll try to track down why the encoding of the URL’s don’t seem to be working properly in this case.

 

I was not able to reproduce the problem using my login.

**Comment by forakshu** [comment] 2017-07-16 03:06
+1. I was browsing through the issues and came across this one. Using my login, i was not able to reproduce this error. Save answers and download answer button functionality worked without submitting the answers.

**Comment by goneall** [comment] 2017-07-16 17:54
Closing the issue since it cannot be reproduced.  If the problem re-occurs, please reopen an issue.

**Closed by goneall** 2017-07-16 17:54 UTC
